Silence spurious ENOENT errors in CI
Our CI runs emit spurious errors/warnings ala:
> Error: ENOENT: no such file or directory, opendir
>        '/home/runner/work/test-fork/test-fork/target/tests/target'

These are coming from the rust-cache action, which erroneously assumes
this directory exists. Make sure it does to silence the noise.